export { default as Hero } from "./Hero";
export { default as HeroWithImages } from "./HeroWithImages";
export { default as HomeLinksBanners } from "./HomeLinksBanners";
export { default as TextSection } from "./TextSection";
export { default as ImageSection } from "./ImageSection";
export { default as Slider } from "./Slider/index.jsx";
export { default as SearchEngines } from "./SearchEngines";
export { default as Reviews } from "./Reviews";
export { default as IFrame } from "./iFrame";
