export const AIRLINES = [
  { id: 16, name: "Aerol\u00edneas Argentinas" },
  { id: 53, name: "Aerom\u00e9xico" },
  { id: 59, name: "Air Canada" },
  { id: 56, name: "Air Europa" },
  { id: 19, name: "Air France" },
  { id: 46, name: "Alitalia" },
  { id: 40, name: "American Airlines" },
  { id: 49, name: "Andes" },
  { id: 36, name: "Austral" },
  { id: 37, name: "Avianca" },
  { id: 62, name: "Boliviana de Aviaci\u00f3n" },
  { id: 47, name: "British Airways" },
  { id: 50, name: "Buquebus" },
  { id: 54, name: "Continental" },
  { id: 48, name: "Conviasa" },
  { id: 39, name: "Copa Airlines" },
  { id: 52, name: "Cubana de Aviaci\u00f3n" },
  { id: 42, name: "Delta Airlines" },
  { id: 60, name: "El Al" },
  { id: 41, name: "Emirates" },
  { id: 155, name: "Flybondi" },
  { id: 17, name: "Gol" },
  { id: 63, name: "Hanh Air" },
  { id: 20, name: "Iberia" },
  { id: 156, name: "Jet Smart" },
  { id: 44, name: "KLM" },
  { id: 15, name: "Lan" },
  { id: 18, name: "Latam" },
  { id: 57, name: "Lufthansa" },
  { id: 64, name: "Qantas" },
  { id: 45, name: "Qatar Airways" },
  { id: 65, name: "Sky Airline" },
  { id: 51, name: "Sol" },
  { id: 43, name: "South African" },
  { id: 66, name: "Swiss" },
  { id: 38, name: "Taca" },
  { id: 67, name: "Tame" },
  { id: 58, name: "Tap" },
  { id: 68, name: "Turkish" },
  { id: 55, name: "United" },
];
