export const OPERATORS = [
  { id: 253, name: "360 Regional Tour Operator" },
  { id: 102, name: "Active Argentina" },
  { id: 82, name: "Adrian de las Sierras" },
  { id: 292, name: "Aero" },
  { id: 53, name: "Aero La Plata" },
  { id: 275, name: "Aeromundo" },
  { id: 191, name: "Agaxtur Argentina" },
  { id: 126, name: "Aguas del Paraiso" },
  { id: 143, name: "Akun Viajes y Turismo" },
  { id: 273, name: "Aleani Travel" },
  { id: 45, name: "All Seasons" },
  { id: 239, name: "All Seasons Agencias" },
  { id: 309, name: "All Seasons Brasil" },
  { id: 170, name: "All Seasons Especial" },
  { id: 247, name: "All Seasons Exclusivo" },
  { id: 227, name: "All Seasons GEA" },
  { id: 238, name: "All Seasons Rosario" },
  { id: 212, name: "All Seasons TN" },
  { id: 43, name: "American" },
  { id: 78, name: "American Executive" },
  { id: 209, name: "American Executive Especial" },
  { id: 73, name: "Amichi" },
  { id: 181, name: "Ananke Turismo" },
  { id: 313, name: "Argard Viajes" },
  { id: 216, name: "Around the World" },
  { id: 115, name: "Assist Card" },
  { id: 128, name: "Atalaya Turismo" },
  { id: 113, name: "Avis" },
  { id: 146, name: "Axioma Travel" },
  { id: 199, name: "Ayax" },
  { id: 152, name: "Ball Tour" },
  { id: 280, name: "Balloon" },
  { id: 157, name: "Be the World" },
  { id: 185, name: "Beach Pro" },
  { id: 276, name: "Beggia" },
  { id: 147, name: "Biblos Travel" },
  { id: 77, name: "Blacktours" },
  { id: 226, name: "Bon Bini" },
  { id: 151, name: "Brownie Tour" },
  { id: 114, name: "Budget" },
  { id: 140, name: "Buenas Vibras Viajes" },
  { id: 61, name: "Buquebus" },
  { id: 312, name: "Caluch Viajes" },
  { id: 289, name: "Caracol Internacional" },
  { id: 300, name: "Caribbean Chile" },
  { id: 177, name: "Carnival Tours" },
  { id: 271, name: "Cerro Bayo" },
  { id: 222, name: "Chasma Servir" },
  { id: 120, name: "Chasma Tours" },
  { id: 110, name: "Che Lagarto Hostels" },
  { id: 285, name: "CIC Travel" },
  { id: 139, name: "Cinco Rumbos" },
  { id: 277, name: "Club de Viajes" },
  { id: 167, name: "Club Med" },
  { id: 133, name: "Colprim Viajes" },
  { id: 282, name: "Comtur" },
  { id: 84, name: "Consolid" },
  { id: 200, name: "Consorcio Travel" },
  { id: 62, name: "Consult House" },
  { id: 154, name: "Consulting Tur" },
  { id: 92, name: "Contiki" },
  { id: 228, name: "Contrastes" },
  { id: 214, name: "Copa Am\u00e9rica" },
  { id: 155, name: "Corima Tours" },
  { id: 116, name: "Coris" },
  { id: 111, name: "Costa Cruceros" },
  { id: 89, name: "Crown" },
  { id: 108, name: "Crucero del Norte" },
  { id: 248, name: "Cuarto Continente" },
  { id: 310, name: "Cuarto Continente Especial" },
  { id: 93, name: "Cuenca del Plata" },
  { id: 66, name: "CVC" },
  { id: 246, name: "De Martino Reisen" },
  { id: 56, name: "Delfos" },
  { id: 186, name: "Despegar.com" },
  { id: 171, name: "Destefanis Travel" },
  { id: 314, name: "Destino Andino" },
  { id: 265, name: "Destinos Tur\u00edsticos Operador Mayorista" },
  { id: 240, name: "Discover the World" },
  { id: 255, name: "DIV" },
  { id: 184, name: "Dopazo & Ravenna" },
  { id: 203, name: "DTP Travel" },
  { id: 287, name: "Dynamic Viajes" },
  { id: 279, name: "Eilat" },
  { id: 281, name: "Empartur" },
  { id: 90, name: "EnCruceros" },
  { id: 298, name: "Euroandino" },
  { id: 94, name: "Eurocentres" },
  { id: 229, name: "Europaba" },
  { id: 44, name: "Eurovips" },
  { id: 286, name: "Eurovips Especial" },
  { id: 124, name: "Eves" },
  { id: 164, name: "Explora" },
  { id: 196, name: "Fan\u00e1ticos de Viajar" },
  { id: 233, name: "Feliz Viajes" },
  { id: 318, name: "Fenix Viajes y Turismo" },
  { id: 236, name: "Flug Viajes y Turismo" },
  { id: 305, name: "Forum" },
  { id: 190, name: "Foster Viajes" },
  { id: 57, name: "Freeway" },
  { id: 225, name: "Freeway Servir" },
  { id: 178, name: "Furlong Fox" },
  { id: 134, name: "FyA Tour" },
  { id: 117, name: "Gala Tour" },
  { id: 198, name: "GIT" },
  { id: 95, name: "Global Explorer" },
  { id: 311, name: "Global Explorer Especial" },
  { id: 58, name: "Grupo Ocho" },
  { id: 307, name: "Grupo Ocho Especial" },
  { id: 317, name: "Grupo Ocho Eventos" },
  { id: 41, name: "Grupo Online" },
  { id: 217, name: "Gur\u00fa" },
  { id: 213, name: "Halifax Viajes" },
  { id: 55, name: "Havanatur" },
  { id: 138, name: "Hi Travel" },
  { id: 206, name: "High Cap" },
  { id: 179, name: "Holland American Line" },
  { id: 96, name: "Hon Travel" },
  { id: 109, name: "Hosteling" },
  { id: 156, name: "Hub Travel" },
  { id: 112, name: "Ibero Cruceros" },
  { id: 269, name: "Ilusiones" },
  { id: 293, name: "Infinity Travel" },
  { id: 71, name: "Intercity" },
  { id: 68, name: "Interlands" },
  { id: 173, name: "Interlands Especial" },
  { id: 274, name: "Interturis" },
  { id: 97, name: "Intrepid" },
  { id: 87, name: "Isla del Sol Travel" },
  { id: 98, name: "Itaparica" },
  { id: 192, name: "Iudica Viola Viajes" },
  { id: 65, name: "Juan Toselli" },
  { id: 297, name: "Julia Grupales" },
  { id: 46, name: "Juli\u00e1 Tours" },
  { id: 224, name: "Julia Tours Servir" },
  { id: 270, name: "Jumping Tour Operador" },
  { id: 237, name: "Kaplan" },
  { id: 144, name: "King Midas" },
  { id: 257, name: "KMB" },
  { id: 175, name: "La Ferrugem Viajes" },
  { id: 268, name: "La Place" },
  { id: 187, name: "Las Apfel de Picasso" },
  { id: 278, name: "Lo Mejor" },
  { id: 48, name: "Logan" },
  { id: 320, name: "Low Cost Operador Mayorista" },
  { id: 135, name: "LuiGa Tour" },
  { id: 193, name: "Luxor" },
  { id: 242, name: "Mahal" },
  { id: 99, name: "Majestic" },
  { id: 100, name: "Marcelo Da Cunha" },
  { id: 291, name: "Marcelo Gutta" },
  { id: 296, name: "Marittima" },
  { id: 321, name: "M\u00e1ximo Destino" },
  { id: 59, name: "MDC" },
  { id: 322, name: "Megatravel" },
  { id: 250, name: "MGT Travel" },
  { id: 267, name: "Miguel Valenti" },
  { id: 161, name: "MSC Cruceros" },
  { id: 159, name: "Mundoreps" },
  { id: 168, name: "N\u00e1utica Viajes" },
  { id: 290, name: "Nites Travel" },
  { id: 104, name: "Nomad" },
  { id: 118, name: "Ola" },
  { id: 323, name: "Ola Especial" },
  { id: 218, name: "Omint Assistance" },
  { id: 125, name: "Opciones Argentinas" },
  { id: 308, name: "Opciones Argentinas Especial" },
  { id: 202, name: "Oppy" },
  { id: 182, name: "OPS Travel" },
  { id: 234, name: "Organfur" },
  { id: 91, name: "Otsi" },
  { id: 306, name: "Paamul" },
  { id: 262, name: "Pacifico" },
  { id: 299, name: "Panamericana Turismo" },
  { id: 63, name: "Passport" },
  { id: 123, name: "Pedraza" },
  { id: 169, name: "Pentagono" },
  { id: 252, name: "Petrabax" },
  { id: 132, name: "Pezzati" },
  { id: 49, name: "Piamonte" },
  { id: 215, name: "Piamonte Especial" },
  { id: 220, name: "Piamonte Servir" },
  { id: 316, name: "Pretti Viajes" },
  { id: 121, name: "Principios" },
  { id: 86, name: "Priority Travel" },
  { id: 163, name: "Pullmantur" },
  { id: 263, name: "Rapel" },
  { id: 60, name: "Ricale" },
  { id: 189, name: "Rincones de Asia" },
  { id: 241, name: "Rincones de Asia" },
  { id: 264, name: "Rol Sol" },
  { id: 141, name: "Rolling Travel" },
  { id: 158, name: "Rotamund" },
  { id: 230, name: "Roteiros" },
  { id: 153, name: "Routelle Viajes" },
  { id: 319, name: "Royal Caribbean" },
  { id: 149, name: "Ryans Travel" },
  { id: 266, name: "Sandals" },
  { id: 261, name: "Sb Super Bus" },
  { id: 172, name: "Sciara Viajes" },
  { id: 176, name: "Scotland Travel" },
  { id: 259, name: "See Travel" },
  { id: 148, name: "Sepean" },
  { id: 258, name: "Setil" },
  { id: 50, name: "Seventur" },
  { id: 235, name: "Showtravel" },
  { id: 136, name: "Siga Turismo" },
  { id: 165, name: "Sobol Viajes" },
  { id: 39, name: "Solways" },
  { id: 301, name: "Solways Chile" },
  { id: 119, name: "Star Winner" },
  { id: 47, name: "Station" },
  { id: 79, name: "Station Travel" },
  { id: 256, name: "STL Servicios Tur\u00edsticos del Litoral" },
  { id: 127, name: "Stoppel Viajes" },
  { id: 174, name: "Sudamerican Tours" },
  { id: 211, name: "Sundance" },
  { id: 105, name: "Surface" },
  { id: 88, name: "T-Block" },
  { id: 160, name: "Taiar Tours" },
  { id: 204, name: "TAM" },
  { id: 64, name: "Thesys" },
  { id: 243, name: "Tiempo Libre" },
  { id: 219, name: "Tije Travel" },
  { id: 106, name: "Tika Group Per\u00fa" },
  { id: 74, name: "Tip Group" },
  { id: 207, name: "Tip Group Especial" },
  { id: 76, name: "Tip Travel" },
  { id: 208, name: "Tip Travel Especial" },
  { id: 223, name: "Tip Travel Servir" },
  { id: 315, name: "TKT Travel" },
  { id: 166, name: "Today Travel" },
  { id: 283, name: "Topdeck Travel" },
  { id: 38, name: "Topdest" },
  { id: 85, name: "Tour Vector" },
  { id: 101, name: "Tourico" },
  { id: 40, name: "Tower Travel" },
  { id: 122, name: "Travel Mark" },
  { id: 42, name: "Trayecto Uno" },
  { id: 210, name: "Trayecto Uno Especial" },
  { id: 221, name: "Trayecto Uno Servir" },
  { id: 254, name: "TRC Mayorista" },
  { id: 103, name: "Trekamerica" },
  { id: 197, name: "Trip Group" },
  { id: 67, name: "TTS Viajes" },
  { id: 295, name: "Tu Viaje" },
  { id: 51, name: "Tucano" },
  { id: 244, name: "Turar" },
  { id: 232, name: "Turismo Aymar\u00e1" },
  { id: 231, name: "Turismo Barbaglia" },
  { id: 205, name: "Turismo High Cap" },
  { id: 302, name: "Turismo Mediterr\u00e1neo" },
  { id: 303, name: "Turismo Rays" },
  { id: 294, name: "Turisteca" },
  { id: 183, name: "UMA Travel" },
  { id: 137, name: "Unitours" },
  { id: 83, name: "Vacaciones Barcelo" },
  { id: 249, name: "Vanguard Marketing" },
  { id: 107, name: "Via Bariloche" },
  { id: 260, name: "Viajando" },
  { id: 142, name: "Vie Tur" },
  { id: 180, name: "Villa de Merlo Turismo" },
  { id: 284, name: "V\u00ednculos Operador Mayorista" },
  { id: 201, name: "Vip Tour" },
  { id: 304, name: "Xotic Travel" },
  { id: 288, name: "Yafar Destinos" },
  { id: 251, name: "Zambra Tour" },
  { id: 145, name: "Zamorano Viajes" },
  { id: 188, name: "Zanellato" },
];
