export const PAYMENT_TYPES = [
  { id: 3, name: "American Express" },
  { id: 23, name: "American Express Platinum-Black" },
  { id: 12, name: "Argencard" },
  { id: 4, name: "Cabal" },
  { id: 7, name: "Dep\u00f3sito Bancario" },
  { id: 10, name: "Diners Club" },
  { id: 6, name: "Efectivo" },
  { id: 2, name: "Mastercard" },
  { id: 22, name: "Mastercard Platinum-Black" },
  { id: 16, name: "MercadoPago" },
  { id: 11, name: "Nativa" },
  { id: 13, name: "Pago F\u00e1cil" },
  { id: 19, name: "PayU" },
  { id: 15, name: "Provincia Pagos" },
  { id: 14, name: "Rapipago" },
  { id: 9, name: "Tarjeta Naranja" },
  { id: 5, name: "Tarjeta Shopping" },
  { id: 18, name: "Todo Pago" },
  { id: 8, name: "Transferencia Bancaria" },
  { id: 1, name: "Visa" },
  { id: 21, name: "Visa Platinum-Black" },
];
